extends: default

rules:
  document-start: disable        # K8s manifests often omit '---'
  line-length: disable           # Ignore long lines (annotations/env vars)
  truthy: disable                # K8s uses "true"/"false" strings
  comments: disable              # Relax comment style
  indentation:
    spaces: 2
    indent-sequences: true
  trailing-spaces: enable
  new-lines:
    type: unix
  empty-values: disable          # Helm templates often have empty values
  key-duplicates: disable        # Helm templates may repeat keys in loops

ignore: |
  charts/**/templates/**         # Ignore Helm templates
  charts/**/values.yaml          # Ignore Helm default values
  environments/**                # Ignore environment-specific overrides
  **/.github/**
