
extends: default

rules:
  document-start: disable
  line-length: disable
  truthy: disable
  comments: disable
  indentation:
    spaces: 2
    indent-sequences: false
  trailing-spaces: enable
  new-lines:
    type: unix
  empty-values: disable
  key-duplicates: disable
  empty-lines: disable

ignore:
  - charts/**         # Ignore all charts (Chart.yaml, templates, index.yaml, etc.)
  - environments/**   # Ignore environment-specific overrides
  - .github/**        # Ignore CI config if you don’t want to lint it
