extends: default

rules:
  document-start: disable
  line-length: disable
  truthy: disable
  comments: disable

  indentation:
    spaces: 2
    indent-sequences: false

  trailing-spaces: enable
  new-lines:
    type: unix

  empty-values: disable
  key-duplicates: enable
  empty-lines: disable

ignore:
  - charts/**          # Ignore all Helm charts
  - charts/**/templates/**  # Ignore all template YAML
  - charts/**/tests/**       # Ignore helm-unittest test YAML
  - environments/**    # Ignore all environment value files
  - .github/**         # Ignore GitHub workflows (optional)
  - "**/*.tpl"         # Ignore Helm helper templates
  - "**/*.yamllint*"   # Ignore own config
