
extends: default

rules:
  document-start: disable
  line-length: disable
  truthy: disable
  comments: disable
  indentation:
    spaces: 2
    indent-sequences: false
  trailing-spaces: enable
  new-lines:
    type: unix
  empty-values: disable
  key-duplicates: disable
  empty-lines: disable    # Disable blank line rule

ignore: |
  charts/**               # Ignore entire charts directory (Chart.yaml, templates, index.yaml)
  environments/**         # Ignore environment-specific overrides
